<?php

use App\Controllers\AboutController;
use App\Controllers\CalendarController;
use App\Controllers\ChantController;
use App\Controllers\FeastController;
use App\Controllers\FormulasController;
use App\Controllers\MemorialController;
use App\Controllers\PrimaryLiturgicalDaysController;
use App\Controllers\SolemnityController;
use App\Controllers\MainController;
use App\Controllers\SeasonController;
use App\HTTPRouter\Route;
Route::get(route: '/calendar/$year/$month', action: [new CalendarController(), 'calendar']);
Route::get(route: '/calendar/$year', action: [new CalendarController(), 'year']);
Route::get(route: '/calendar', action: [new CalendarController(), 'calendarMain']);
Route::get(route: '/chants/primary-liturgical-days/$day/$name', action: [new PrimaryLiturgicalDaysController(), 'mass']);
Route::get(route: '/chants/primary-liturgical-days/$name', action: [new PrimaryLiturgicalDaysController(), 'day']);
Route::get(route: '/chants/primary-liturgical-days', action: [new PrimaryLiturgicalDaysController(), 'days']);
Route::get(route: '/chants/seasons/$season/$week', action: [new SeasonController(), 'day']);
Route::get(route: '/chants/seasons/$season', action: [new SeasonController(), 'season']);
Route::get(route: '/chants/seasons', action: [new SeasonController(), 'seasons']);
Route::get(route: '/chants/formulas', action: [new FormulasController(), 'formulas']);
Route::get(route: '/chants/solemnities/$name', action: [new SolemnityController(), 'solemnity']);
Route::get(route: '/chants/solemnities', action: [new SolemnityController(), 'solemnities']);
Route::get(route: '/chants/feasts/$name', action: [new FeastController(), 'feast']);
Route::get(route: '/chants/feasts', action: [new FeastController(), 'feasts']);
Route::get(route: '/chants/memorials/$name', action: [new MemorialController(), 'feast']);
Route::get(route: '/chants/memorials', action: [new MemorialController(), 'feasts']);
Route::get(route: '/chants', action: [new ChantController(), 'categoryList']);
Route::get(route: '/about', action: [new AboutController(), 'index']);
Route::get(route: '/', action: [new MainController(), 'main']);
